
[platformio]
default_envs = mini_esp32s3_plc_mini

[env:mini_esp32]
platform = espressif32
framework = arduino
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
	knolleary/PubSubClient@^2.8
	marian-craciunescu/ESP32Ping @ ^1.7
	https://github.com/me-no-dev/ESPAsyncWebServer.git
	https://github.com/me-no-dev/AsyncTCP.git
monitor_speed = 115200
check_skip_packages = yes

[env:mini_esp32s3]
extends = env:mini_esp32
board = esp32-s3-devkitc-1
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv

[env:mini_esp32s3_plc_mini]
extends = env:mini_esp32s3
board_build.arduino.memory_type = qio_qspi ; Flash QIO, PSRAM Quad SPI AP 3v3
build_flags = 
    -DBOARD_ESP32S3_PLC_MINI
    -DBOARD_HAS_PSRAM

[env:mini_esp32s3_rs485_can]
extends = env:mini_esp32s3
board_build.arduino.memory_type = qio_opi ; Flash (qio), PSRAM Octal SPI (opi)
build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -DBOARD_HAS_PSRAM
    -DBOARD_ESP32S3_RS485_CAN

[env:esp32c3]
extends = env:mini_esp32
board = esp32-c3-devkitm-1

